### ISSUE TITLE
US10 - Noter les caves

### ISSUE THREAD

**Issue by lpierillas** [Oxynos/ViensDansMaCave#10]
En tant que membre
Je veux pouvoir noter les caves des autres membres
Afin de donner mon avis.

**Comment by L3TZ** [comment]
En tant que membre
Je veux pouvoir modifier la note d’une cave
Afin de modifier mon avis en fonction de l’évolution des bouteilles

**Comment by L3TZ** [comment]
Il faudrait intégrer les modifs de Cédric avant de pouvoir valider complètement cette US, elle en est trop dépendante. Par contre il y a un bug quand tu valides ton vote sans avoir sélectionné une note (erreur 500, cast de null vers float impossible)
