### ISSUE TITLE
US8 - Consulter les caves des membres

### ISSUE THREAD

**Issue by lpierillas** [Oxynos/ViensDansMaCave#8]
En tant que membre 
Je veux pouvoir consulter les caves des autres membres
Afin de savoir quels vins sont présents dans leurs caves.

**Comment by L3TZ** [comment]
les tests d'intégration ne passent pas. Tu as modifié le jeu de test, du coup certains "vieux" tests ne passent plus il faut que tu corriges ça pour que je puisse valider l'US ;)

**Comment by Oxynos** [comment]
les tests passent je pense que la US peut être validée, je passe à l'intégration après

**Comment by L3TZ** [comment]
tu peux intégrer
